name: LowLevel_NeuralNetwork

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7.4', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    
    - name: Build library
      run: |
        make build-lib

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        make dev-env

    - name: Lint
      if: matrix.python-version != '3.5'
      run: |
        make lint

    - name: Test
      run: |
        make test
